wmsentry.settings:
    type: config_object
    label: Settings
    mapping:
        dsn:
            type: string
            label: 'Data Source Name. A representation of the configuration required by the Sentry SDK.'
        release:
            type: string
            label: 'A string representing the version of your code that is deployed to an environment.'
        environment:
            type: string
            label: 'A string representing the environment of this application (e.g. local, development, production)'
        include_stacktrace_func_args:
            type: boolean
            label: 'Determines whether function arguments should be included in the stack trace.'
        excluded_exceptions:
            type: sequence
            label: 'Sometimes you may want to skip capturing certain exceptions. This option sets the FQCN of the classes of the exceptions that you don’t want to capture. The check is done using the instanceof operator against each item of the array and if at least one of them passes the event will be discarded.'
            sequence:
                type: string
                label: 'Class name'
        excluded_tags:
            type: mapping
            label: 'A list of tags that - if present on an event - will cause the captured exception to be skipped.'
            mapping:
                tag:
                    type: string
                    label: Tag
                value:
                    type: string
                    label: Value
        log_levels:
            type: mapping
            label: 'The RFC log levels that should be captured by Sentry'
            mapping:
                1:
                    type: integer
                    label: 'Emergency'
                2:
                    type: integer
                    label: 'Alert'
                3:
                    type: integer
                    label: 'Critical'
                4:
                    type: integer
                    label: 'Error'
                5:
                    type: integer
                    label: 'Warning'
                6:
                    type: integer
                    label: 'Notice'
                7:
                    type: integer
                    label: 'Info'
                8:
                    type: integer
                    label: 'Debug'
        in_app_include:
            type: sequence
            label: 'A list of string prefixes of module names that belong to the app. This option takes precedence over in_app_exclude.'
            sequence:
                type: string
                label: 'Path prefix'
        in_app_exclude:
            type: sequence
            label: 'A list of string prefixes of module names that do not belong to the app, but rather to third-party packages. Modules considered not part of the app will be hidden from stack traces by default. This option can be overridden using in_app_include.'
            sequence:
                type: string
                label: 'Path prefix'
